# DockerFile for an environment into which firedrake can be installed.

FROM ubuntu:22.04

# Update and install required packages for Firedrake
USER root
RUN apt-get update \
    && apt-get -y dist-upgrade \
    && DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata \
    && apt-get -y install curl vim docker.io \
                          openssh-client build-essential autoconf automake \
                          cmake gfortran git libopenblas-serial-dev python3-pandas\
                          libtool python3-dev python3-pip python3-tk python3-venv \
                          python3-requests zlib1g-dev libboost-dev sudo \
                          bison flex \
                          liboce-ocaf-dev \
                          swig graphviz \
    && rm -rf /var/lib/apt/lists/*

# Use a more sane locale
ENV LC_ALL C.UTF-8

# Set up user so that we do not run as root
RUN useradd -m -s /bin/bash -G sudo firedrake && \
    echo "firedrake:docker" | chpasswd && \
    echo "firedrake ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers && \
    ldconfig

USER firedrake
WORKDIR /home/firedrake

# Now install firedrake
RUN curl -O https://raw.githubusercontent.com/kothah/firedrake/master/scripts/firedrake-install
RUN bash -c "python3 firedrake-install --no-package-manager --disable-ssh --venv-name=firedrake"

RUN bash -c "echo '. /home/firedrake/firedrake/bin/activate' >> ~/.bashrc"
RUN export PYTHONPATH=/home/firedrake/firedrake_pf:$PYTHONPATH
